name: build-core

on:
  workflow_dispatch: 

jobs:
  build-core:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh
    
    steps:
    - name: 'Build Core'
      run: |
        $env:CHERE_INVOKING = 'yes'
        $env:MSYSTEM = 'CLANG64'
        $env:MSYS2_PATH_TYPE = 'inherit'
        git clone https://github.com/necrosisy/nekobox_core.git --recursive
        cd nekobox_core
        C:\msys64\usr\bin\bash.exe -lc "./libs/get_source.sh"
        C:\msys64\usr\bin\bash.exe -lc "GOOS=windows GOARCH=amd64 bash libs/build_go.sh"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with: 
          name: nekobox-core
          path: '${{ github.workspace }}/nekobox_core/deployment/windows64/'
